trigger:
  branches:
    include:
      - dev

pool:
  name: SandboxAgent

stages:
- stage: DevDeploy
  jobs:
    - job: DeployToDev
      steps:
        - task: AzureWebApp@1
          inputs:
            azureSubscription: 'nimbus-azure-connection'
            appType: 'webAppLinux'
            appName: 'nimbus-notes-frontend-dev'
            package: '$(System.DefaultWorkingDirectory)/**/*.zip'