trigger:
  branches:
    include:
      - main
      - dev

pool:
  name: SandboxAgent

variables:
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  devAppName: 'nimbus-notes-frontend-dev'
  devResourceGroup: 'rg-nimbus-dev'
  stagingAppName: 'nimbus-notes-frontend-staging'
  stagingResourceGroup: 'rg-nimbus-staging'

stages:
# ========================================
# BUILD STAGE
# ========================================
- stage: BuildFrontend
  displayName: 'Build Frontend'
  jobs:
    - job: DeployToDev
      steps:
        # Archive the source code into a zip file
        - task: ArchiveFiles@2
          inputs:
            rootFolderOrFile: '$(workingDirectory)'
            includeRootFolder: false
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/frontend-static.zip'
            replaceExistingArchive: true

        # Deploy the zip file to Azure Web App
        - task: AzureWebApp@1
          inputs:
            azureSubscription: 'nimbus-azure-connection'
            appType: 'webAppLinux'
            appName: 'nimbus-notes-frontend-dev'
            package: '$(Build.ArtifactStagingDirectory)/app.zip'