trigger:
  branches:
    include:
      - main
      - dev

pool:
  name: SandboxAgent

variables:
  nodeVersion: '22.x'
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  devAppName: 'nimbus-notes-frontend-dev'
  devResourceGroup: 'rg-nimbus-dev'
  prodAppName: 'nimbus-notes-frontend-prod'
  prodResourceGroup: 'rg-nimbus-prod'

stages:
# ========================================
# BUILD STAGE
# ========================================
- stage: BuildFrontend
  displayName: 'Build Frontend'
  jobs:
    - job: BuildJob
      displayName: 'Build Static Frontend'
      steps:
        - task: ArchiveFiles@2
          displayName: '📦 Archive Static Files'
          inputs:
            rootFolderOrFile: '$(workingDirectory)/frontend'
            includeRootFolder: false
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/frontend-static.zip'
            replaceExistingArchive: true

        - task: PublishBuildArtifacts@1
          displayName: '📤 Publish Build Artifact'
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'frontend-drop'
            publishLocation: 'Container'

# ========================================
# DEPLOY TO DEVELOPMENT
# ========================================
- stage: DeployToDev
  displayName: 'Deploy to Dev Web App'
  dependsOn: BuildFrontend
  condition: eq(variables['Build.SourceBranchName'], 'dev')
  jobs:
    - deployment: DevDeploy
      environment: 'development'
      strategy:
        runOnce:
          deploy:
            steps:
              - task: DownloadBuildArtifacts@1
                displayName: '⬇️ Download Build Artifact'
                inputs:
                  buildType: 'current'
                  downloadType: 'single'
                  artifactName: 'frontend-drop'
                  downloadPath: '$(System.ArtifactsDirectory)'

              - task: AzureWebApp@1
                displayName: '🚀 Deploy to Dev Web App'
                inputs:
                  azureSubscription: 'nimbus-azure-connection'
                  appType: 'webAppLinux'
                  appName: '$(devAppName)'
                  resourceGroupName: '$(devResourceGroup)'
                  package: '$(System.ArtifactsDirectory)/frontend-drop/frontend-static.zip'

# ========================================
# DEPLOY TO PRODUCTION
# ========================================
- stage: DeployToProd
  displayName: 'Deploy to Production Web App'
  dependsOn: BuildFrontend
  condition: eq(variables['Build.SourceBranchName'], 'main')
  jobs:
    - deployment: ProdDeploy
      environment: 'production'
      strategy:
        runOnce:
          deploy:
            steps:
              - task: DownloadBuildArtifacts@1
                displayName: '⬇️ Download Build Artifact'
                inputs:
                  buildType: 'current'
                  downloadType: 'single'
                  artifactName: 'frontend-drop'
                  downloadPath: '$(System.ArtifactsDirectory)'

              - task: AzureWebApp@1
                displayName: '🚀 Deploy to Production Web App'
                inputs:
                  azureSubscription: 'nimbus-azure-connection'
                  appType: 'webAppLinux'
                  appName: '$(prodAppName)'
                  resourceGroupName: '$(prodResourceGroup)'
                  package: '$(System.ArtifactsDirectory)/frontend-drop/frontend-static.zip'
